-- CREATES SEQUENCES & TABLES
CREATE SEQUENCE post_id_seq INCREMENT 1 MINVALUE 1;
CREATE TABLE Post (
  id INTEGER NOT NULL DEFAULT nextval('post_id_seq'),
  assunto VARCHAR(200) NOT NULL,
  conteudo VARCHAR(5000) NOT NULL,
  PRIMARY KEY (id)
);

CREATE SEQUENCE comentario_id_seq INCREMENT 1 MINVALUE 1;
CREATE TABLE Comentario (
  id INTEGER NOT NULL DEFAULT nextval('comentario_id_seq'),
  post INTEGER NOT NULL,
  conteudo VARCHAR(5000) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (post) REFERENCES Post (id) ON DELETE CASCADE
);

CREATE SEQUENCE album_id_seq INCREMENT 1 MINVALUE 1;
CREATE TABLE Album (
  id INTEGER NOT NULL DEFAULT nextval('album_id_seq'),
  nome VARCHAR(200) NOT NULL,
  descricao VARCHAR(5000),
  PRIMARY KEY (id)
);

CREATE SEQUENCE foto_id_seq INCREMENT 1 MINVALUE 1;
CREATE TABLE Foto (
  id INTEGER NOT NULL DEFAULT nextval('foto_id_seq'),
  album INTEGER NOT NULL,
  descricao VARCHAR(5000),
  PRIMARY KEY (id),
  FOREIGN KEY (album) REFERENCES Album (id) ON DELETE CASCADE
);

-- ALTERS

ALTER TABLE Post ADD COLUMN horario TIMESTAMP NOT NULL DEFAULT NOW()
ALTER TABLE Comentario ADD COLUMN horario TIMESTAMP NOT NULL DEFAULT NOW()
ALTER TABLE Album ADD COLUMN horario TIMESTAMP NOT NULL DEFAULT NOW()
ALTER TABLE Foto ADD COLUMN horario TIMESTAMP NOT NULL DEFAULT NOW()
